server:
  port: ${SERVER_PORT:8089}

spring:
  application:
    name: payment-service

#  kafka:
#    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

  security:
    oauth2:
      # ===== Validate incoming JWTs =====
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}

      # ===== OAuth2 Client (client_credentials) =====
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_TOKEN_URI}

# ===== Legacy Adapter =====
legacy:
  service:
    url: ${LEGACY_SERVICE_URL}

# ===== Internal Services =====
account:
  service: ${ACCOUNT_SERVICE}

user:
  service: ${USER_SERVICE}

## ===== Kafka Topics =====
#kafka:
#  topic:
#    payment-events: payment-events
