server:
  port: 8089 # Run Payment Service on 8089 to avoid conflict with Legacy (8081)

spring:
  application:
    name: payment-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: true

  security:
    # ===== Resource Server (validate incoming JWTs) =====
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bankino

      # ===== OAuth2 Client (to call other services) =====
      client:
        registration:
          keycloak:
            client-id: ${keycloak.client-id}
            client-secret: ${keycloak.client-secret}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token

legacy:
  service:
    url: http://localhost:8085 # The URL where your LegacyAdapterService is running

kafka:
  topic:
    payment-events: payment-events

account:
  service: http://localhost:8084

user:
  service: http://localhost:8083

# ===== Keycloak environment variables =====
keycloak:
  client-id: payment-service
  client-secret: tbHITJJmxe9GzHy8SmgwWV3GThSqoX0O
  auth-server-url: http://localhost:8080
  realm: bankino
