apiVersion: v1
kind: Namespace
metadata:
  name: banking-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: banking-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: 342547628532.dkr.ecr.us-west-2.amazonaws.com/ebanking:payment-latest
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: LEGACY_SERVICE_URL
              value: "http://legacy-adapter-public:80"
            - name: ACCOUNT_SERVICE
              value: "http://account-service:80"
            - name: USER_SERVICE
              value: "http://user-service:80"
            - name: SERVER_PORT
              value: "8089"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: banking-ns
spec:
  type: LoadBalancer
  selector:
    app: payment-service
  ports:
    - port: 80
      targetPort: 8089
